name: neo4j-graph-contest 

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.10
  - jupyterlab
  - jupyterlab_widgets
  - ipywidgets
  - pandas
  - python-dotenv=1.0.0
  - openai
  - neo4j-python-driver 

